apiVersion: v1
kind: Service
metadata:
  name: dcsf19-api-routing-demo
  namespace: infra-k8s
  labels:
    app: dcsf19-api-routing-demo
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32880
  selector:
    app: dcsf19-api-routing-demo

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dcsf19-api-routing-demo
  namespace: infra-k8s
spec:
  selector:
    matchLabels:
      app: dcsf19-api-routing-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: dcsf19-api-routing-demo
    spec:
      restartPolicy: Always
      containers:
        - name: dcsf19-api-routing-demo
          image: dckr/dcsf19-api-routing-demo:1-kubernetes
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi


