apiVersion: v1
kind: Service
metadata:
  name: dcsf19-api-routing-demo
  namespace: default
  labels:
    app: dcsf19-api-routing-demo
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32880
  selector:
    app: dcsf19-api-routing-demo

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dcsf19-api-routing-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: dcsf19-api-routing-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: dcsf19-api-routing-demo
    spec:
      containers:
        - name: dcsf19-api-routing-demo
          image: dckr/dcsf19-api-routing-demo:1-kubernetes
          ports:
            - containerPort: 80


