version: '3.7'

services:
  web:
    image: dckr/dcsf19-api-routing-demo:1-swarm
    ports:
      - mode: host
        protocol: tcp
        target: 80
    deploy:
      replicas: 3
    environment:
      SERVICE_NAME: dcsf19-api-routing-demo
