version: '3.7'

services:
  web:
    image: dckr/dcsf19-api-routing-demo:1-swarm
    ports:
      - mode: host
        protocol: tcp
        target: 80
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      resources:
        limits:
            memory: 128M
        reservations:
            memory: 128M
    environment:
      SERVICE_NAME: dcsf19-api-routing-demo
